#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

cd libSalinitySolverLib; wclean; cd ../

wclean

cd salinityBoussinesqPimpleEqDyMFoam; wclean; cd ../

# ----------------------------------------------------------------- end-of-file
