#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

cd libSalinitySolverLib; wmake libso; cd ../

wmake

cd salinityBoussinesqPimpleEqDyMFoam; wmake; cd ../

# ----------------------------------------------------------------- end-of-file
